// iso-639-3

export const langCodes = {
    "cmn": "Mandarin Chinese",
    "spa": "Spanish",
    "eng": "English",
    "rus": "Russian",
    "arb": "Standard Arabic",
    "ben": "Bengali",
    "hin": "Hindi",
    "por": "Portuguese",
    "ind": "Indonesian",
    "jpn": "Japanese",
    "fra": "French",
    "deu": "German",
    "jav": "Javanese (Latin)",  // Consolidated "Javanese (Javanese)" and "Javanese (Latin)"
    "kor": "Korean",
    "tel": "Telugu",
    "vie": "Vietnamese",
    "mar": "Marathi",
    "ita": "Italian",
    "tam": "Tamil",
    "tur": "Turkish",
    "urd": "Urdu",
    "guj": "Gujarati",
    "pol": "Polish",
    "ukr": "Ukrainian",
    "kan": "Kannada",
    "mai": "Maithili",
    "mal": "Malayalam",
    "pes": "Iranian Persian",
    "mya": "Burmese",
    "swh": "Swahili (individual language)",
    "sun": "Sundanese",
    "ron": "Romanian",
    "pan": "Panjabi",
    "bho": "Bhojpuri",
    "amh": "Amharic",
    "hau": "Hausa",
    "fuv": "Nigerian Fulfulde",
    "bos": "Bosnian (Latin)",  // Consolidated "Bosnian (Cyrillic)" and "Bosnian (Latin)"
    "hrv": "Croatian",
    "nld": "Dutch",
    "srp": "Serbian (Latin)",  // Consolidated "Serbian (Cyrillic)" and "Serbian (Latin)"
    "tha": "Thai",
    "ckb": "Central Kurdish",
    "yor": "Yoruba",
    "uzn": "Northern Uzbek (Latin)",  // Consolidated "Northern Uzbek (Cyrillic)" and "Northern Uzbek (Latin)"
    "zlm": "Malay (individual language) (Latin)",  // Consolidated "Malay (individual language) (Arabic)" and "Malay (individual language) (Latin)"
    "ibo": "Igbo",
    "npi": "Nepali (individual language)",
    "ceb": "Cebuano",
    "skr": "Saraiki",
    "tgl": "Tagalog",
    "hun": "Hungarian",
    "azj": "North Azerbaijani (Latin)",  // Consolidated "North Azerbaijani (Cyrillic)" and "North Azerbaijani (Latin)"
    "sin": "Sinhala",
    "koi": "Komi-Permyak",
    "ell": "Modern Greek (1453-)",
    "ces": "Czech",
    "mag": "Magahi",
    "run": "Rundi",
    "bel": "Belarusian",
    "plt": "Plateau Malagasy",
    "qug": "Chimborazo Highland Quichua",
    "mad": "Madurese",
    "nya": "Nyanja",
    "zyb": "Yongbei Zhuang",
    "pbu": "Northern Pashto",
    "kin": "Kinyarwanda",
    "zul": "Zulu",
    "bul": "Bulgarian",
    "swe": "Swedish",
    "lin": "Lingala",
    "som": "Somali",
    "hms": "Southern Qiandong Miao",
    "hnj": "Hmong Njua",
    "ilo": "Iloko",
    "kaz": "Kazakh",
    "uig": "Uighur (Latin)",  // Consolidated "Uighur (Arabic)" and "Uighur (Latin)"
    "hat": "Haitian",
    "khm": "Khmer",
    "prs": "Dari",
    "hil": "Hiligaynon",
    "sna": "Shona",
    "tat": "Tatar",
    "xho": "Xhosa",
    "hye": "Armenian",
    "min": "Minangkabau",
    "afr": "Afrikaans",
    "lua": "Luba-Lulua",
    "sat": "Santali",
    "bod": "Tibetan",
    "tir": "Tigrinya",
    "fin": "Finnish",
    "slk": "Slovak",
    "tuk": "Turkmen (Latin)",  // Consolidated "Turkmen (Cyrillic)" and "Turkmen (Latin)"
    "dan": "Danish",
    "nob": "Norwegian Bokmål",
    "suk": "Sukuma",
    "als": "Tosk Albanian",
    "sag": "Sango",
    "nno": "Norwegian Nynorsk",
    "heb": "Hebrew",
    "mos": "Mossi",
    "tgk": "Tajik",
    "cat": "Catalan",
    "sot": "Southern Sotho",
    "kat": "Georgian",
    "bcl": "Central Bikol",
    "glg": "Galician",
    "lao": "Lao",
    "lit": "Lithuanian",
    "umb": "Umbundu",
    "tsn": "Tswana",
    "vec": "Venetian",
    "nso": "Pedi",
    "ban": "Balinese",
    "bug": "Buginese",
    "knc": "Central Kanuri",
    "kng": "Koongo",
    "ibb": "Ibibio",
    "lug": "Ganda",
    "ace": "Achinese",
    "bam": "Bambara",
    "tzm": "Central Atlas Tamazight",
    "ydd": "Eastern Yiddish",
    "kmb": "Kimbundu",
    "lun": "Lunda",
    "shn": "Shan",
    "war": "Waray (Philippines)",
    "dyu": "Dyula",
    "wol": "Wolof",
    "kir": "Kirghiz",
    "nds": "Low German",
    "fuf": "Pular",
    "mkd": "Macedonian",
    "vmw": "Makhuwa",
    "zgh": "Standard Moroccan Tamazight",
    "ewe": "Ewe",
    "khk": "Halh Mongolian",
    "slv": "Slovenian",
    "ayr": "Central Aymara",
    "bem": "Bemba (Zambia)",
    "emk": "Eastern Maninkakan",
    "bci": "Baoulé",
    "bum": "Bulu (Cameroon)",
    "epo": "Esperanto",
    "pam": "Pampanga",
    "tiv": "Tiv",
    "tpi": "Tok Pisin",
    "ven": "Venda",
    "ssw": "Swati",
    "nyn": "Nyankole",
    "kbd": "Kabardian",
    "iii": "Sichuan Yi",
    "yao": "Yao",
    "lvs": "Standard Latvian",
    "quz": "Cusco Quechua",
    "src": "Logudorese Sardinian"
}
